// vue-table/src/App.vue
<template>
  <div id="app">
    <div v-bind:data-state="current.toStrings()">
      <div class="selectbox"></div>

      <div>
        <button>New</button>
        <button :disabled="!current.matches('selection.SINGLE_SELECTION')">Open</button>
        <button :disabled="current.matches('selection.EMPTY_SELECTION')">Delete</button>

        <table>
          <thead>
            <tr>
              <th>Id</th>
              <th>Name</th>
              <th>Address</th>
              <th>Email</th>
            </tr>
          </thead>
          <tbody>
            <tr
              v-for="row in current.context.rows"
              v-bind:key="row.id"
              v-bind:data-row-id="row.id"
              v-on:click="evt => send({type: evt.type, evt, id: row.id})"
              v-bind:class="{ selected: current.context.selectedIds.includes(row.id) }"
              ref="rows"
            >
              <td>{{row.id}}</td>
              <td>{{row.name}}</td>
              <td>{{row.address}}</td>
              <td>{{row.email}}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>

<script>
import { interpret } from "xstate";
import faker from "faker";
import { tableMachine, findElementsInSelectArea } from "xstate-table";

export default {
  name: "Vue-Table",
  created() {
    this.toggleService
      .onTransition(state => {
        this.current = state;
      })
      .start();
  },
  data() {
    const machine = tableMachine.withConfig(
      {},
      {
        rows: Array.from({ length: 100 }, (_, i) => ({
          id: i + 10000,
          name: faker.name.findName(),
          address: faker.address.streetAddress(),
          email: faker.internet.email()
        })),
        selectedIds: [10002],
        delay: 300,
        findElementsInSelectArea: (ctx, selectArea) =>
          findElementsInSelectArea(ctx, selectArea, () => this.$refs.rows)
      }
    );

    return {
      toggleService: interpret(machine),
      current: machine.initialState
    };
  },
  mounted() {
    window.addEventListener("mousedown", evt =>
      this.send({ type: evt.type, evt })
    );
    window.addEventListener("mousemove", evt =>
      this.send({ type: evt.type, evt })
    );
    window.addEventListener("mouseup", evt =>
      this.send({ type: evt.type, evt })
    );
  },
  methods: {
    send(event) {
      this.toggleService.send(event);
    }
  }
};
</script>

<style>
:root {
  --theme-color: #42b883;
}
</style>

// angular-table/src/app/app.component.ts
import {
  Component,
  HostListener,
  ViewChildren,
  QueryList,
  ElementRef,
  OnInit
} from "@angular/core";
import { tableMachine, findElementsInSelectArea } from "xstate-table";
import faker from "faker";
import { TableMachine } from "./table-machine";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"],
  providers: [TableMachine]
})
export class AppComponent implements OnInit {
  title = "angular-table";

  @ViewChildren("rows", { read: ElementRef }) rows: QueryList<ElementRef>;

  constructor(public machine: TableMachine) {}

  ngOnInit() {
    this.machine.setupMachine(
      tableMachine.withConfig(
        {},
        {
          rows: Array.from({ length: 100 }, (_, i) => ({
            id: i + 10000,
            name: faker.name.findName(),
            address: faker.address.streetAddress(),
            email: faker.internet.email()
          })),
          selectedIds: [10002],
          delay: 300,
          findElementsInSelectArea: (ctx, selectArea) =>
            findElementsInSelectArea(ctx, selectArea, () =>
              this.rows.toArray().map(r => r.nativeElement)
            )
        }
      )
    );
  }

  rowClick(evt, id) {
    this.machine.actions$.next({ type: evt.type, evt, id });
  }

  @HostListener("body:mousedown", ["$event"])
  @HostListener("body:mousemove", ["$event"])
  @HostListener("body:mouseup", ["$event"])
  mouse(evt: MouseEvent) {
    this.machine.actions$.next({ type: evt.type, evt });
  }
}

<div
  *ngIf="((machine.state$ | async) || [{}])[0] as state"
  [attr.data-state]="state.toStrings()"
>
  <div class="selectbox"></div>
  <div>
    <button>New</button>
    <button [disabled]="!state.matches('selection.SINGLE_SELECTION')">
      Open
    </button>
    <button [disabled]="state.matches('selection.EMPTY_SELECTION')">
      Delete
    </button>

    <table>
      <thead>
        <tr>
          <th>Id</th>
          <th>Name</th>
          <th>Address</th>
          <th>Email</th>
        </tr>
      </thead>
      <tbody>
        <tr
          [attr.data-row-id]="row.id"
          (click)="rowClick($event, row.id)"
          [class.selected]="state.context.selectedIds.includes(row.id)"
          *ngFor="let row of state.context.rows"
          #rows
        >
          <td>{{ row.id }}</td>
          <td>{{ row.name }}</td>
          <td>{{ row.address }}</td>
          <td>{{ row.email }}</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
